# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 514)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(14, 10, 841, 431))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.connectButton = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icons/bonus/icons-24/arrow-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectButton.setIcon(icon)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 0, 0, 1, 2)
        self.disconnectButton = QtWidgets.QPushButton(self.widget)
        self.disconnectButton.setIcon(icon)
        self.disconnectButton.setObjectName("disconnectButton")
        self.gridLayout.addWidget(self.disconnectButton, 0, 2, 1, 2)
        self.UploadButton = QtWidgets.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../icons/bonus/icons-24/arrow-090.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UploadButton.setIcon(icon1)
        self.UploadButton.setObjectName("UploadButton")
        self.gridLayout.addWidget(self.UploadButton, 0, 4, 1, 2)
        self.downloadButton = QtWidgets.QPushButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../icons/bonus/icons-24/arrow-270.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadButton.setIcon(icon2)
        self.downloadButton.setObjectName("downloadButton")
        self.gridLayout.addWidget(self.downloadButton, 0, 6, 1, 1)
        self.newdirButton = QtWidgets.QPushButton(self.widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../icons/bonus/icons-24/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newdirButton.setIcon(icon3)
        self.newdirButton.setObjectName("newdirButton")
        self.gridLayout.addWidget(self.newdirButton, 0, 7, 1, 2)
        self.deleteButton = QtWidgets.QPushButton(self.widget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../icons/bonus/icons-24/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon4)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 0, 9, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(self.widget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../icons/bonus/icons-24/arrow-circle-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon5)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 0, 10, 1, 3)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.hostEdit = QtWidgets.QLineEdit(self.widget)
        self.hostEdit.setObjectName("hostEdit")
        self.gridLayout.addWidget(self.hostEdit, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 2)
        self.usernameEdit = QtWidgets.QLineEdit(self.widget)
        self.usernameEdit.setObjectName("usernameEdit")
        self.gridLayout.addWidget(self.usernameEdit, 1, 5, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 7, 1, 1)
        self.passwordEdit = QtWidgets.QLineEdit(self.widget)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridLayout.addWidget(self.passwordEdit, 1, 8, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 11, 1, 1)
        self.portEdit = QtWidgets.QLineEdit(self.widget)
        self.portEdit.setObjectName("portEdit")
        self.gridLayout.addWidget(self.portEdit, 1, 12, 1, 1)
        self.sshBox = QtWidgets.QCheckBox(self.widget)
        self.sshBox.setObjectName("sshBox")
        self.gridLayout.addWidget(self.sshBox, 1, 13, 1, 1)
        self.infoBox = QtWidgets.QPlainTextEdit(self.widget)
        self.infoBox.setObjectName("infoBox")
        self.gridLayout.addWidget(self.infoBox, 2, 1, 1, 12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.UploadButton.setText(_translate("MainWindow", "Upload"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.newdirButton.setText(_translate("MainWindow", "New Dir"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.label.setText(_translate("MainWindow", "Host:"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.label_4.setText(_translate("MainWindow", "Port:"))
        self.sshBox.setText(_translate("MainWindow", "SSH"))
